//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phan4_2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanSu
    {
        public int MaNV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public Nullable<System.DateTime> Ngay_BD { get; set; }
        public Nullable<int> MaPB { get; set; }
        public int ID_Luong { get; set; }
    
        public virtual Luong Luong { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
